## Introduction to PyTorch

In [ ]:
import torch

x = torch.empty(5, 3)
print(x)
print(x.size())
print('__________________________')
y = torch.randn(3,4, dtype=torch.float)
print(y)
print(y[:, 1])  # print 2nd cloumn
print(y[0,:])   # print 1st row

PyTorch 中的矩阵计算
-------------

``@`` 和 ``*`` 代表矩阵的两种相乘方式：``@``表示常规的数学上定义的矩阵相乘；``*``表示两个矩阵对应位置处的两个元素相乘。<p>
``x.dot(y)`` : 向量乘积, x，y均为一维向量<p>
``*``和``torch.mul()``等同:表示相同shape矩阵点乘，即对应位置相乘，得到矩阵有相同的shape。<p>
``@``和``torch.mm(a, b)``以及``torch.matmul(a,b)``等同：正常矩阵相乘，要求a的列数与b的行数相同。<p>
``torch.mv(X, w)``:是矩阵和向量相乘.第一个参数是矩阵，第二个参数只能是一维向量,等价于X乘以w<p>
``Y.t()``:矩阵Y的转置。

In [3]:
# 两个一维向量的乘积运算, 则返回两个向量的点积运算结果
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = torch.matmul(x,y)
print(z)
print(z.shape)
print('--------------------------------')


# 一个一维向量和一个二维矩阵的乘积运算
# 若x为一维，y为二维，则先将x的一维向量扩充到二维(维数前面插入长度为1的新维度)，然后进行矩阵乘积，得到结果后再将此维度去掉，得到的与x的维度相同。
x = torch.tensor([1,2])
y = torch.tensor([[3,4,5],
                  [6,7,8]])
z = torch.matmul(x,y)
print(z)
print(z.shape)
print('--------------------------------')

# 一个二维矩阵和一个一维向量的乘积运算
# 若y为一维，x为二维，则先将y的一维向量扩充到二维(维数前面插入长度为1的新维度)，然后进行矩阵乘积，得到结果后再将此维度去掉，得到的与y的维度相同。
y = torch.tensor([1,2,3])
x = torch.tensor([[3,4,5],
                  [6,7,8]])
z = torch.matmul(x,y)
print(z)
print(z.shape)
print('--------------------------------')


# torch.mv(a, w1)矩阵乘向量
w1 = torch.tensor([1, 2, 1])
A = torch.tensor([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1],
])

res1 = torch.mv(A, w1)
res11 = torch.mv(A, w1.t())

print("torch.mv(a, w1)=")
print(f'{format(res1)}')
print("torch.mv(a, w1.t()=")
print(f'{format(res11)}')

print('--------------------------------')


B = torch.tensor([
    [1, 1, 1, 3],
    [0, 1, 1, 5],
    [0, 0, 1, 9],
])

w2 = torch.tensor([2,3,4,5])
w3 = torch.tensor([1,2,3])

print(f'{format(B@w2)}')
print(f'{w3@B}')

tensor(11)
torch.Size([])
--------------------------------
tensor([15, 18, 21])
torch.Size([3])
--------------------------------
tensor([26, 44])
torch.Size([2])
--------------------------------
torch.mv(a, w1)=
tensor([4, 3, 1])
torch.mv(a, w1.t()=
tensor([4, 3, 1])
--------------------------------
tensor([24, 32, 49])
tensor([ 1,  3,  6, 40])
